version: "3.7"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - type: bind
        source: /storage/sabnzbd/config
        target: /config
      - type: bind
        source: /storage/media/downloads
        target: /downloads
      - type: bind
        source: /storage/media/incomplete-downloads
        target: /incomplete-downloads
    ports:
      - "8080:8080"
    restart: unless-stopped